#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManagementLib
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="6113")]
	public partial class CSQLLogTableDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertCDeviceFaultLogDto(CDeviceFaultLogDto instance);
    partial void UpdateCDeviceFaultLogDto(CDeviceFaultLogDto instance);
    partial void DeleteCDeviceFaultLogDto(CDeviceFaultLogDto instance);
    partial void InsertCSystemLogDto(CSystemLogDto instance);
    partial void UpdateCSystemLogDto(CSystemLogDto instance);
    partial void DeleteCSystemLogDto(CSystemLogDto instance);
    partial void InsertCTelegramLogDto(CTelegramLogDto instance);
    partial void UpdateCTelegramLogDto(CTelegramLogDto instance);
    partial void DeleteCTelegramLogDto(CTelegramLogDto instance);
    partial void InsertCICCardLogDto(CICCardLogDto instance);
    partial void UpdateCICCardLogDto(CICCardLogDto instance);
    partial void DeleteCICCardLogDto(CICCardLogDto instance);
    partial void InsertCDeviceStatusLogDto(CDeviceStatusLogDto instance);
    partial void UpdateCDeviceStatusLogDto(CDeviceStatusLogDto instance);
    partial void DeleteCDeviceStatusLogDto(CDeviceStatusLogDto instance);
    #endregion
		
		public CSQLLogTableDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSQLLogTableDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSQLLogTableDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSQLLogTableDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CDeviceFaultLogDto> CDeviceFaultLogDto
		{
			get
			{
				return this.GetTable<CDeviceFaultLogDto>();
			}
		}
		
		public System.Data.Linq.Table<CSystemLogDto> CSystemLogDto
		{
			get
			{
				return this.GetTable<CSystemLogDto>();
			}
		}
		
		public System.Data.Linq.Table<CTelegramLogDto> CTelegramLogDto
		{
			get
			{
				return this.GetTable<CTelegramLogDto>();
			}
		}
		
		public System.Data.Linq.Table<CICCardLogDto> CICCardLogDto
		{
			get
			{
				return this.GetTable<CICCardLogDto>();
			}
		}
		
		public System.Data.Linq.Table<CDeviceStatusLogDto> CDeviceStatusLogDto
		{
			get
			{
				return this.GetTable<CDeviceStatusLogDto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.devicefaultlog")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CDeviceFaultLogDto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _warehouse;
		
		private System.Nullable<int> _devicecode;
		
		private string _faultdescp;
		
		private System.Nullable<System.DateTime> _time;
		
		private string _optcode;
		
		private System.Nullable<int> _color;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnwarehouseChanging(System.Nullable<int> value);
    partial void OnwarehouseChanged();
    partial void OndevicecodeChanging(System.Nullable<int> value);
    partial void OndevicecodeChanged();
    partial void OnfaultdescpChanging(string value);
    partial void OnfaultdescpChanged();
    partial void OntimeChanging(System.Nullable<System.DateTime> value);
    partial void OntimeChanged();
    partial void OnoptcodeChanging(string value);
    partial void OnoptcodeChanged();
    partial void OncolorChanging(System.Nullable<int> value);
    partial void OncolorChanged();
    #endregion
		
		public CDeviceFaultLogDto()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_warehouse", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<int> warehouse
		{
			get
			{
				return this._warehouse;
			}
			set
			{
				if ((this._warehouse != value))
				{
					this.OnwarehouseChanging(value);
					this.SendPropertyChanging();
					this._warehouse = value;
					this.SendPropertyChanged("warehouse");
					this.OnwarehouseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_devicecode", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> devicecode
		{
			get
			{
				return this._devicecode;
			}
			set
			{
				if ((this._devicecode != value))
				{
					this.OndevicecodeChanging(value);
					this.SendPropertyChanging();
					this._devicecode = value;
					this.SendPropertyChanged("devicecode");
					this.OndevicecodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_faultdescp", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string faultdescp
		{
			get
			{
				return this._faultdescp;
			}
			set
			{
				if ((this._faultdescp != value))
				{
					this.OnfaultdescpChanging(value);
					this.SendPropertyChanging();
					this._faultdescp = value;
					this.SendPropertyChanged("faultdescp");
					this.OnfaultdescpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<System.DateTime> time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optcode", DbType="NVarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string optcode
		{
			get
			{
				return this._optcode;
			}
			set
			{
				if ((this._optcode != value))
				{
					this.OnoptcodeChanging(value);
					this.SendPropertyChanging();
					this._optcode = value;
					this.SendPropertyChanged("optcode");
					this.OnoptcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<int> color
		{
			get
			{
				return this._color;
			}
			set
			{
				if ((this._color != value))
				{
					this.OncolorChanging(value);
					this.SendPropertyChanging();
					this._color = value;
					this.SendPropertyChanged("color");
					this.OncolorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.systemlog")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CSystemLogDto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _logid;
		
		private string _logdescp;
		
		private System.Nullable<System.DateTime> _curtime;
		
		private string _optcode;
		
		private string _optname;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlogidChanging(int value);
    partial void OnlogidChanged();
    partial void OnlogdescpChanging(string value);
    partial void OnlogdescpChanged();
    partial void OncurtimeChanging(System.Nullable<System.DateTime> value);
    partial void OncurtimeChanged();
    partial void OnoptcodeChanging(string value);
    partial void OnoptcodeChanged();
    partial void OnoptnameChanging(string value);
    partial void OnoptnameChanged();
    #endregion
		
		public CSystemLogDto()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int logid
		{
			get
			{
				return this._logid;
			}
			set
			{
				if ((this._logid != value))
				{
					this.OnlogidChanging(value);
					this.SendPropertyChanging();
					this._logid = value;
					this.SendPropertyChanged("logid");
					this.OnlogidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logdescp", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string logdescp
		{
			get
			{
				return this._logdescp;
			}
			set
			{
				if ((this._logdescp != value))
				{
					this.OnlogdescpChanging(value);
					this.SendPropertyChanging();
					this._logdescp = value;
					this.SendPropertyChanged("logdescp");
					this.OnlogdescpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curtime", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<System.DateTime> curtime
		{
			get
			{
				return this._curtime;
			}
			set
			{
				if ((this._curtime != value))
				{
					this.OncurtimeChanging(value);
					this.SendPropertyChanging();
					this._curtime = value;
					this.SendPropertyChanged("curtime");
					this.OncurtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optcode", DbType="NVarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string optcode
		{
			get
			{
				return this._optcode;
			}
			set
			{
				if ((this._optcode != value))
				{
					this.OnoptcodeChanging(value);
					this.SendPropertyChanging();
					this._optcode = value;
					this.SendPropertyChanged("optcode");
					this.OnoptcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optname", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string optname
		{
			get
			{
				return this._optname;
			}
			set
			{
				if ((this._optname != value))
				{
					this.OnoptnameChanging(value);
					this.SendPropertyChanging();
					this._optname = value;
					this.SendPropertyChanged("optname");
					this.OnoptnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.telegramlog")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CTelegramLogDto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _time;
		
		private string _logtype;
		
		private string _telegramhead;
		
		private System.Nullable<int> _devicecode;
		
		private string _iccode;
		
		private string _carinfo;
		
		private string _slotinfo;
		
		private string _srcaddr;
		
		private string _destaddr;
		
		private System.Nullable<int> _telegramid;
		
		private System.Nullable<int> _direction;
		
		private System.Nullable<int> _warehouse;
		
		private System.Nullable<int> _destdirection;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntimeChanging(System.Nullable<System.DateTime> value);
    partial void OntimeChanged();
    partial void OnlogtypeChanging(string value);
    partial void OnlogtypeChanged();
    partial void OntelegramheadChanging(string value);
    partial void OntelegramheadChanged();
    partial void OndevicecodeChanging(System.Nullable<int> value);
    partial void OndevicecodeChanged();
    partial void OniccodeChanging(string value);
    partial void OniccodeChanged();
    partial void OncarinfoChanging(string value);
    partial void OncarinfoChanged();
    partial void OnslotinfoChanging(string value);
    partial void OnslotinfoChanged();
    partial void OnsrcaddrChanging(string value);
    partial void OnsrcaddrChanged();
    partial void OndestaddrChanging(string value);
    partial void OndestaddrChanged();
    partial void OntelegramidChanging(System.Nullable<int> value);
    partial void OntelegramidChanged();
    partial void OndirectionChanging(System.Nullable<int> value);
    partial void OndirectionChanged();
    partial void OnwarehouseChanging(System.Nullable<int> value);
    partial void OnwarehouseChanged();
    partial void OndestdirectionChanging(System.Nullable<int> value);
    partial void OndestdirectionChanged();
    #endregion
		
		public CTelegramLogDto()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<System.DateTime> time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logtype", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string logtype
		{
			get
			{
				return this._logtype;
			}
			set
			{
				if ((this._logtype != value))
				{
					this.OnlogtypeChanging(value);
					this.SendPropertyChanging();
					this._logtype = value;
					this.SendPropertyChanged("logtype");
					this.OnlogtypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telegramhead", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string telegramhead
		{
			get
			{
				return this._telegramhead;
			}
			set
			{
				if ((this._telegramhead != value))
				{
					this.OntelegramheadChanging(value);
					this.SendPropertyChanging();
					this._telegramhead = value;
					this.SendPropertyChanged("telegramhead");
					this.OntelegramheadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_devicecode", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<int> devicecode
		{
			get
			{
				return this._devicecode;
			}
			set
			{
				if ((this._devicecode != value))
				{
					this.OndevicecodeChanging(value);
					this.SendPropertyChanging();
					this._devicecode = value;
					this.SendPropertyChanged("devicecode");
					this.OndevicecodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iccode", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string iccode
		{
			get
			{
				return this._iccode;
			}
			set
			{
				if ((this._iccode != value))
				{
					this.OniccodeChanging(value);
					this.SendPropertyChanging();
					this._iccode = value;
					this.SendPropertyChanged("iccode");
					this.OniccodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carinfo", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string carinfo
		{
			get
			{
				return this._carinfo;
			}
			set
			{
				if ((this._carinfo != value))
				{
					this.OncarinfoChanging(value);
					this.SendPropertyChanging();
					this._carinfo = value;
					this.SendPropertyChanged("carinfo");
					this.OncarinfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slotinfo", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string slotinfo
		{
			get
			{
				return this._slotinfo;
			}
			set
			{
				if ((this._slotinfo != value))
				{
					this.OnslotinfoChanging(value);
					this.SendPropertyChanging();
					this._slotinfo = value;
					this.SendPropertyChanged("slotinfo");
					this.OnslotinfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_srcaddr", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string srcaddr
		{
			get
			{
				return this._srcaddr;
			}
			set
			{
				if ((this._srcaddr != value))
				{
					this.OnsrcaddrChanging(value);
					this.SendPropertyChanging();
					this._srcaddr = value;
					this.SendPropertyChanged("srcaddr");
					this.OnsrcaddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destaddr", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public string destaddr
		{
			get
			{
				return this._destaddr;
			}
			set
			{
				if ((this._destaddr != value))
				{
					this.OndestaddrChanging(value);
					this.SendPropertyChanging();
					this._destaddr = value;
					this.SendPropertyChanged("destaddr");
					this.OndestaddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telegramid", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public System.Nullable<int> telegramid
		{
			get
			{
				return this._telegramid;
			}
			set
			{
				if ((this._telegramid != value))
				{
					this.OntelegramidChanging(value);
					this.SendPropertyChanging();
					this._telegramid = value;
					this.SendPropertyChanged("telegramid");
					this.OntelegramidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direction", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public System.Nullable<int> direction
		{
			get
			{
				return this._direction;
			}
			set
			{
				if ((this._direction != value))
				{
					this.OndirectionChanging(value);
					this.SendPropertyChanging();
					this._direction = value;
					this.SendPropertyChanged("direction");
					this.OndirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_warehouse", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public System.Nullable<int> warehouse
		{
			get
			{
				return this._warehouse;
			}
			set
			{
				if ((this._warehouse != value))
				{
					this.OnwarehouseChanging(value);
					this.SendPropertyChanging();
					this._warehouse = value;
					this.SendPropertyChanged("warehouse");
					this.OnwarehouseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destdirection", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public System.Nullable<int> destdirection
		{
			get
			{
				return this._destdirection;
			}
			set
			{
				if ((this._destdirection != value))
				{
					this.OndestdirectionChanging(value);
					this.SendPropertyChanging();
					this._destdirection = value;
					this.SendPropertyChanged("destdirection");
					this.OndestdirectionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.iccardlog")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CICCardLogDto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _iccode;
		
		private System.Nullable<int> _ictype;
		
		private System.Nullable<System.DateTime> _starttime;
		
		private System.Nullable<System.DateTime> _endtime;
		
		private string _calculatedays;
		
		private System.Nullable<int> _feetype;
		
		private System.Nullable<double> _tariffnorm;
		
		private System.Nullable<double> _payablefee;
		
		private System.Nullable<double> _actualfee;
		
		private string _username;
		
		private string _optcode;
		
		private System.Nullable<System.DateTime> _paymenttime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OniccodeChanging(string value);
    partial void OniccodeChanged();
    partial void OnictypeChanging(System.Nullable<int> value);
    partial void OnictypeChanged();
    partial void OnstarttimeChanging(System.Nullable<System.DateTime> value);
    partial void OnstarttimeChanged();
    partial void OnendtimeChanging(System.Nullable<System.DateTime> value);
    partial void OnendtimeChanged();
    partial void OncalculatedaysChanging(string value);
    partial void OncalculatedaysChanged();
    partial void OnfeetypeChanging(System.Nullable<int> value);
    partial void OnfeetypeChanged();
    partial void OntariffnormChanging(System.Nullable<double> value);
    partial void OntariffnormChanged();
    partial void OnpayablefeeChanging(System.Nullable<double> value);
    partial void OnpayablefeeChanged();
    partial void OnactualfeeChanging(System.Nullable<double> value);
    partial void OnactualfeeChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnoptcodeChanging(string value);
    partial void OnoptcodeChanged();
    partial void OnpaymenttimeChanging(System.Nullable<System.DateTime> value);
    partial void OnpaymenttimeChanged();
    #endregion
		
		public CICCardLogDto()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iccode", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string iccode
		{
			get
			{
				return this._iccode;
			}
			set
			{
				if ((this._iccode != value))
				{
					this.OniccodeChanging(value);
					this.SendPropertyChanging();
					this._iccode = value;
					this.SendPropertyChanged("iccode");
					this.OniccodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ictype", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> ictype
		{
			get
			{
				return this._ictype;
			}
			set
			{
				if ((this._ictype != value))
				{
					this.OnictypeChanging(value);
					this.SendPropertyChanging();
					this._ictype = value;
					this.SendPropertyChanged("ictype");
					this.OnictypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_starttime", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<System.DateTime> starttime
		{
			get
			{
				return this._starttime;
			}
			set
			{
				if ((this._starttime != value))
				{
					this.OnstarttimeChanging(value);
					this.SendPropertyChanging();
					this._starttime = value;
					this.SendPropertyChanged("starttime");
					this.OnstarttimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endtime", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<System.DateTime> endtime
		{
			get
			{
				return this._endtime;
			}
			set
			{
				if ((this._endtime != value))
				{
					this.OnendtimeChanging(value);
					this.SendPropertyChanging();
					this._endtime = value;
					this.SendPropertyChanged("endtime");
					this.OnendtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calculatedays", DbType="nvarchar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string calculatedays
		{
			get
			{
				return this._calculatedays;
			}
			set
			{
				if ((this._calculatedays != value))
				{
					this.OncalculatedaysChanging(value);
					this.SendPropertyChanging();
					this._calculatedays = value;
					this.SendPropertyChanged("calculatedays");
					this.OncalculatedaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_feetype", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<int> feetype
		{
			get
			{
				return this._feetype;
			}
			set
			{
				if ((this._feetype != value))
				{
					this.OnfeetypeChanging(value);
					this.SendPropertyChanging();
					this._feetype = value;
					this.SendPropertyChanged("feetype");
					this.OnfeetypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tariffnorm", DbType="Float")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<double> tariffnorm
		{
			get
			{
				return this._tariffnorm;
			}
			set
			{
				if ((this._tariffnorm != value))
				{
					this.OntariffnormChanging(value);
					this.SendPropertyChanging();
					this._tariffnorm = value;
					this.SendPropertyChanged("tariffnorm");
					this.OntariffnormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payablefee", DbType="Float")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.Nullable<double> payablefee
		{
			get
			{
				return this._payablefee;
			}
			set
			{
				if ((this._payablefee != value))
				{
					this.OnpayablefeeChanging(value);
					this.SendPropertyChanging();
					this._payablefee = value;
					this.SendPropertyChanged("payablefee");
					this.OnpayablefeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actualfee", DbType="Float")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<double> actualfee
		{
			get
			{
				return this._actualfee;
			}
			set
			{
				if ((this._actualfee != value))
				{
					this.OnactualfeeChanging(value);
					this.SendPropertyChanging();
					this._actualfee = value;
					this.SendPropertyChanged("actualfee");
					this.OnactualfeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optcode", DbType="NVarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string optcode
		{
			get
			{
				return this._optcode;
			}
			set
			{
				if ((this._optcode != value))
				{
					this.OnoptcodeChanging(value);
					this.SendPropertyChanging();
					this._optcode = value;
					this.SendPropertyChanged("optcode");
					this.OnoptcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymenttime", DbType="DateTime ")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public System.Nullable<System.DateTime> paymenttime
		{
			get
			{
				return this._paymenttime;
			}
			set
			{
				if ((this._paymenttime != value))
				{
					this.OnpaymenttimeChanging(value);
					this.SendPropertyChanging();
					this._paymenttime = value;
					this.SendPropertyChanged("paymenttime");
					this.OnpaymenttimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.devicestatuslog")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CDeviceStatusLogDto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _warehouse;
		
		private System.Nullable<int> _devicecode;
		
		private string _deviceaddr;
		
		private System.Nullable<System.DateTime> _time;
		
		private System.Nullable<int> _devicemode;
		
		private System.Nullable<int> _devicetype;
		
		private System.Nullable<int> _halltype;
		
		private System.Nullable<int> _curtasktype;
		
		private System.Nullable<int> _isavailable;
		
		private System.Nullable<int> _isgetoutcar;
		
		private System.Nullable<int> _instep;
		
		private System.Nullable<int> _outstep;
		
		private System.Nullable<int> _isable;
		
		private System.Nullable<int> _runstep;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnwarehouseChanging(System.Nullable<int> value);
    partial void OnwarehouseChanged();
    partial void OndevicecodeChanging(System.Nullable<int> value);
    partial void OndevicecodeChanged();
    partial void OndeviceaddrChanging(string value);
    partial void OndeviceaddrChanged();
    partial void OntimeChanging(System.Nullable<System.DateTime> value);
    partial void OntimeChanged();
    partial void OndevicemodeChanging(System.Nullable<int> value);
    partial void OndevicemodeChanged();
    partial void OndevicetypeChanging(System.Nullable<int> value);
    partial void OndevicetypeChanged();
    partial void OnhalltypeChanging(System.Nullable<int> value);
    partial void OnhalltypeChanged();
    partial void OncurtasktypeChanging(System.Nullable<int> value);
    partial void OncurtasktypeChanged();
    partial void OnisavailableChanging(System.Nullable<int> value);
    partial void OnisavailableChanged();
    partial void OnisgetoutcarChanging(System.Nullable<int> value);
    partial void OnisgetoutcarChanged();
    partial void OninstepChanging(System.Nullable<int> value);
    partial void OninstepChanged();
    partial void OnoutstepChanging(System.Nullable<int> value);
    partial void OnoutstepChanged();
    partial void OnisableChanging(System.Nullable<int> value);
    partial void OnisableChanged();
    partial void OnrunstepChanging(System.Nullable<int> value);
    partial void OnrunstepChanged();
    #endregion
		
		public CDeviceStatusLogDto()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_warehouse", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<int> warehouse
		{
			get
			{
				return this._warehouse;
			}
			set
			{
				if ((this._warehouse != value))
				{
					this.OnwarehouseChanging(value);
					this.SendPropertyChanging();
					this._warehouse = value;
					this.SendPropertyChanged("warehouse");
					this.OnwarehouseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_devicecode", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> devicecode
		{
			get
			{
				return this._devicecode;
			}
			set
			{
				if ((this._devicecode != value))
				{
					this.OndevicecodeChanging(value);
					this.SendPropertyChanging();
					this._devicecode = value;
					this.SendPropertyChanged("devicecode");
					this.OndevicecodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deviceaddr", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string deviceaddr
		{
			get
			{
				return this._deviceaddr;
			}
			set
			{
				if ((this._deviceaddr != value))
				{
					this.OndeviceaddrChanging(value);
					this.SendPropertyChanging();
					this._deviceaddr = value;
					this.SendPropertyChanged("deviceaddr");
					this.OndeviceaddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<System.DateTime> time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_devicemode", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<int> devicemode
		{
			get
			{
				return this._devicemode;
			}
			set
			{
				if ((this._devicemode != value))
				{
					this.OndevicemodeChanging(value);
					this.SendPropertyChanging();
					this._devicemode = value;
					this.SendPropertyChanged("devicemode");
					this.OndevicemodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_devicetype", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<int> devicetype
		{
			get
			{
				return this._devicetype;
			}
			set
			{
				if ((this._devicetype != value))
				{
					this.OndevicetypeChanging(value);
					this.SendPropertyChanging();
					this._devicetype = value;
					this.SendPropertyChanged("devicetype");
					this.OndevicetypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_halltype", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<int> halltype
		{
			get
			{
				return this._halltype;
			}
			set
			{
				if ((this._halltype != value))
				{
					this.OnhalltypeChanging(value);
					this.SendPropertyChanging();
					this._halltype = value;
					this.SendPropertyChanged("halltype");
					this.OnhalltypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curtasktype", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.Nullable<int> curtasktype
		{
			get
			{
				return this._curtasktype;
			}
			set
			{
				if ((this._curtasktype != value))
				{
					this.OncurtasktypeChanging(value);
					this.SendPropertyChanging();
					this._curtasktype = value;
					this.SendPropertyChanged("curtasktype");
					this.OncurtasktypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isavailable", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<int> isavailable
		{
			get
			{
				return this._isavailable;
			}
			set
			{
				if ((this._isavailable != value))
				{
					this.OnisavailableChanging(value);
					this.SendPropertyChanging();
					this._isavailable = value;
					this.SendPropertyChanged("isavailable");
					this.OnisavailableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isgetoutcar", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public System.Nullable<int> isgetoutcar
		{
			get
			{
				return this._isgetoutcar;
			}
			set
			{
				if ((this._isgetoutcar != value))
				{
					this.OnisgetoutcarChanging(value);
					this.SendPropertyChanging();
					this._isgetoutcar = value;
					this.SendPropertyChanged("isgetoutcar");
					this.OnisgetoutcarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_instep", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public System.Nullable<int> instep
		{
			get
			{
				return this._instep;
			}
			set
			{
				if ((this._instep != value))
				{
					this.OninstepChanging(value);
					this.SendPropertyChanging();
					this._instep = value;
					this.SendPropertyChanged("instep");
					this.OninstepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outstep", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public System.Nullable<int> outstep
		{
			get
			{
				return this._outstep;
			}
			set
			{
				if ((this._outstep != value))
				{
					this.OnoutstepChanging(value);
					this.SendPropertyChanging();
					this._outstep = value;
					this.SendPropertyChanged("outstep");
					this.OnoutstepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isable", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public System.Nullable<int> isable
		{
			get
			{
				return this._isable;
			}
			set
			{
				if ((this._isable != value))
				{
					this.OnisableChanging(value);
					this.SendPropertyChanging();
					this._isable = value;
					this.SendPropertyChanged("isable");
					this.OnisableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_runstep", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public System.Nullable<int> runstep
		{
			get
			{
				return this._runstep;
			}
			set
			{
				if ((this._runstep != value))
				{
					this.OnrunstepChanging(value);
					this.SendPropertyChanging();
					this._runstep = value;
					this.SendPropertyChanged("runstep");
					this.OnrunstepChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
}
#pragma warning restore 1591
