#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManagementLib
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_6096BJ")]
	public partial class CSQLOtherTableDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertCDeviceFaultDto(CDeviceFaultDto instance);
    partial void UpdateCDeviceFaultDto(CDeviceFaultDto instance);
    partial void DeleteCDeviceFaultDto(CDeviceFaultDto instance);
    partial void InsertCSoundDto(CSoundDto instance);
    partial void UpdateCSoundDto(CSoundDto instance);
    partial void DeleteCSoundDto(CSoundDto instance);
    partial void InsertCLedContentDto(CLedContentDto instance);
    partial void UpdateCLedContentDto(CLedContentDto instance);
    partial void DeleteCLedContentDto(CLedContentDto instance);
    partial void InsertCTariffDto(CTariffDto instance);
    partial void UpdateCTariffDto(CTariffDto instance);
    partial void DeleteCTariffDto(CTariffDto instance);
    partial void InsertCWorkQueueDto(CWorkQueueDto instance);
    partial void UpdateCWorkQueueDto(CWorkQueueDto instance);
    partial void DeleteCWorkQueueDto(CWorkQueueDto instance);
    #endregion
		
		public CSQLOtherTableDataContext() : 
				base(global::DatabaseManagementLib.Properties.Settings.Default.db_6096BJConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CSQLOtherTableDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSQLOtherTableDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSQLOtherTableDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSQLOtherTableDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CDeviceFaultDto> CDeviceFaultDto
		{
			get
			{
				return this.GetTable<CDeviceFaultDto>();
			}
		}
		
		public System.Data.Linq.Table<CSoundDto> CSoundDto
		{
			get
			{
				return this.GetTable<CSoundDto>();
			}
		}
		
		public System.Data.Linq.Table<CLedContentDto> CLedContentDto
		{
			get
			{
				return this.GetTable<CLedContentDto>();
			}
		}
		
		public System.Data.Linq.Table<CTariffDto> CTariffDto
		{
			get
			{
				return this.GetTable<CTariffDto>();
			}
		}
		
		public System.Data.Linq.Table<CWorkQueueDto> CWorkQueueDto
		{
			get
			{
				return this.GetTable<CWorkQueueDto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.devicefault")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CDeviceFaultDto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _faultdescp;
		
		private System.Nullable<int> _faultaddress;
		
		private System.Nullable<int> _color;
		
		private System.Nullable<int> _isable;
		
		private System.Nullable<int> _devicecode;
		
		private System.Nullable<int> _warehouse;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnfaultdescpChanging(string value);
    partial void OnfaultdescpChanged();
    partial void OnfaultaddressChanging(System.Nullable<int> value);
    partial void OnfaultaddressChanged();
    partial void OncolorChanging(System.Nullable<int> value);
    partial void OncolorChanged();
    partial void OnisableChanging(System.Nullable<int> value);
    partial void OnisableChanged();
    partial void OndevicecodeChanging(System.Nullable<int> value);
    partial void OndevicecodeChanged();
    partial void OnwarehouseChanging(System.Nullable<int> value);
    partial void OnwarehouseChanged();
    #endregion
		
		public CDeviceFaultDto()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_faultdescp", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string faultdescp
		{
			get
			{
				return this._faultdescp;
			}
			set
			{
				if ((this._faultdescp != value))
				{
					this.OnfaultdescpChanging(value);
					this.SendPropertyChanging();
					this._faultdescp = value;
					this.SendPropertyChanged("faultdescp");
					this.OnfaultdescpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_faultaddress", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> faultaddress
		{
			get
			{
				return this._faultaddress;
			}
			set
			{
				if ((this._faultaddress != value))
				{
					this.OnfaultaddressChanging(value);
					this.SendPropertyChanging();
					this._faultaddress = value;
					this.SendPropertyChanged("faultaddress");
					this.OnfaultaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<int> color
		{
			get
			{
				return this._color;
			}
			set
			{
				if ((this._color != value))
				{
					this.OncolorChanging(value);
					this.SendPropertyChanging();
					this._color = value;
					this.SendPropertyChanged("color");
					this.OncolorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isable", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<int> isable
		{
			get
			{
				return this._isable;
			}
			set
			{
				if ((this._isable != value))
				{
					this.OnisableChanging(value);
					this.SendPropertyChanging();
					this._isable = value;
					this.SendPropertyChanged("isable");
					this.OnisableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_devicecode", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<int> devicecode
		{
			get
			{
				return this._devicecode;
			}
			set
			{
				if ((this._devicecode != value))
				{
					this.OndevicecodeChanging(value);
					this.SendPropertyChanging();
					this._devicecode = value;
					this.SendPropertyChanged("devicecode");
					this.OndevicecodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_warehouse", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<int> warehouse
		{
			get
			{
				return this._warehouse;
			}
			set
			{
				if ((this._warehouse != value))
				{
					this.OnwarehouseChanging(value);
					this.SendPropertyChanging();
					this._warehouse = value;
					this.SendPropertyChanged("warehouse");
					this.OnwarehouseChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sound")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CSoundDto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _soundcode;
		
		private string _soundname;
		
		private string _soundcontent;
		
		private System.Nullable<int> _soundishand;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsoundcodeChanging(string value);
    partial void OnsoundcodeChanged();
    partial void OnsoundnameChanging(string value);
    partial void OnsoundnameChanged();
    partial void OnsoundcontentChanging(string value);
    partial void OnsoundcontentChanged();
    partial void OnsoundishandChanging(System.Nullable<int> value);
    partial void OnsoundishandChanged();
    #endregion
		
		public CSoundDto()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soundcode", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string soundcode
		{
			get
			{
				return this._soundcode;
			}
			set
			{
				if ((this._soundcode != value))
				{
					this.OnsoundcodeChanging(value);
					this.SendPropertyChanging();
					this._soundcode = value;
					this.SendPropertyChanged("soundcode");
					this.OnsoundcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soundname", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string soundname
		{
			get
			{
				return this._soundname;
			}
			set
			{
				if ((this._soundname != value))
				{
					this.OnsoundnameChanging(value);
					this.SendPropertyChanging();
					this._soundname = value;
					this.SendPropertyChanged("soundname");
					this.OnsoundnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soundcontent", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string soundcontent
		{
			get
			{
				return this._soundcontent;
			}
			set
			{
				if ((this._soundcontent != value))
				{
					this.OnsoundcontentChanging(value);
					this.SendPropertyChanging();
					this._soundcontent = value;
					this.SendPropertyChanged("soundcontent");
					this.OnsoundcontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soundishand", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<int> soundishand
		{
			get
			{
				return this._soundishand;
			}
			set
			{
				if ((this._soundishand != value))
				{
					this.OnsoundishandChanging(value);
					this.SendPropertyChanging();
					this._soundishand = value;
					this.SendPropertyChanged("soundishand");
					this.OnsoundishandChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ledcontent")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CLedContentDto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ledcontent;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnledcontentChanging(string value);
    partial void OnledcontentChanged();
    #endregion
		
		public CLedContentDto()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ledcontent", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string ledcontent
		{
			get
			{
				return this._ledcontent;
			}
			set
			{
				if ((this._ledcontent != value))
				{
					this.OnledcontentChanging(value);
					this.SendPropertyChanging();
					this._ledcontent = value;
					this.SendPropertyChanged("ledcontent");
					this.OnledcontentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tariff")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CTariffDto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _iccardtype;
		
		private System.Nullable<int> _feetype;
		
		private string _tariffdescp;
		
		private System.Nullable<int> _isworkday;
		
		private string _workpeakperiod;
		
		private System.Nullable<float> _workdayquotafee;
		
		private string _workpeakfirstunit;
		
		private string _worknonpeakfirstunit;
		
		private string _workpeakinunitfee;
		
		private string _workpeakoutunitfee;
		
		private string _worknonpeakinunitfee;
		
		private string _worknonpeakoutunitfee;
		
		private string _nonworkpeakperiod;
		
		private System.Nullable<float> _nonworkdayquotafee;
		
		private string _nonworkpeakfirstunit;
		
		private string _nonworknonpeakfirstunit;
		
		private string _nonworkpeakinunitfee;
		
		private string _nonworkpeakoutunitfee;
		
		private string _nonworknonpeakinunitfee;
		
		private string _nonworknonpeakoutunitfee;
		
		private System.Nullable<float> _fee;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OniccardtypeChanging(System.Nullable<int> value);
    partial void OniccardtypeChanged();
    partial void OnfeetypeChanging(System.Nullable<int> value);
    partial void OnfeetypeChanged();
    partial void OntariffdescpChanging(string value);
    partial void OntariffdescpChanged();
    partial void OnisworkdayChanging(System.Nullable<int> value);
    partial void OnisworkdayChanged();
    partial void OnworkpeakperiodChanging(string value);
    partial void OnworkpeakperiodChanged();
    partial void OnworkdayquotafeeChanging(System.Nullable<float> value);
    partial void OnworkdayquotafeeChanged();
    partial void OnworkpeakfirstunitChanging(string value);
    partial void OnworkpeakfirstunitChanged();
    partial void OnworknonpeakfirstunitChanging(string value);
    partial void OnworknonpeakfirstunitChanged();
    partial void OnworkpeakinunitfeeChanging(string value);
    partial void OnworkpeakinunitfeeChanged();
    partial void OnworkpeakoutunitfeeChanging(string value);
    partial void OnworkpeakoutunitfeeChanged();
    partial void OnworknonpeakinunitfeeChanging(string value);
    partial void OnworknonpeakinunitfeeChanged();
    partial void OnworknonpeakoutunitfeeChanging(string value);
    partial void OnworknonpeakoutunitfeeChanged();
    partial void OnnonworkpeakperiodChanging(string value);
    partial void OnnonworkpeakperiodChanged();
    partial void OnnonworkdayquotafeeChanging(System.Nullable<float> value);
    partial void OnnonworkdayquotafeeChanged();
    partial void OnnonworkpeakfirstunitChanging(string value);
    partial void OnnonworkpeakfirstunitChanged();
    partial void OnnonworknonpeakfirstunitChanging(string value);
    partial void OnnonworknonpeakfirstunitChanged();
    partial void OnnonworkpeakinunitfeeChanging(string value);
    partial void OnnonworkpeakinunitfeeChanged();
    partial void OnnonworkpeakoutunitfeeChanging(string value);
    partial void OnnonworkpeakoutunitfeeChanged();
    partial void OnnonworknonpeakinunitfeeChanging(string value);
    partial void OnnonworknonpeakinunitfeeChanged();
    partial void OnnonworknonpeakoutunitfeeChanging(string value);
    partial void OnnonworknonpeakoutunitfeeChanged();
    partial void OnfeeChanging(System.Nullable<float> value);
    partial void OnfeeChanged();
    #endregion
		
		public CTariffDto()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iccardtype", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<int> iccardtype
		{
			get
			{
				return this._iccardtype;
			}
			set
			{
				if ((this._iccardtype != value))
				{
					this.OniccardtypeChanging(value);
					this.SendPropertyChanging();
					this._iccardtype = value;
					this.SendPropertyChanged("iccardtype");
					this.OniccardtypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_feetype", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> feetype
		{
			get
			{
				return this._feetype;
			}
			set
			{
				if ((this._feetype != value))
				{
					this.OnfeetypeChanging(value);
					this.SendPropertyChanging();
					this._feetype = value;
					this.SendPropertyChanged("feetype");
					this.OnfeetypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tariffdescp", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string tariffdescp
		{
			get
			{
				return this._tariffdescp;
			}
			set
			{
				if ((this._tariffdescp != value))
				{
					this.OntariffdescpChanging(value);
					this.SendPropertyChanging();
					this._tariffdescp = value;
					this.SendPropertyChanged("tariffdescp");
					this.OntariffdescpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isworkday", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<int> isworkday
		{
			get
			{
				return this._isworkday;
			}
			set
			{
				if ((this._isworkday != value))
				{
					this.OnisworkdayChanging(value);
					this.SendPropertyChanging();
					this._isworkday = value;
					this.SendPropertyChanged("isworkday");
					this.OnisworkdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workpeakperiod", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string workpeakperiod
		{
			get
			{
				return this._workpeakperiod;
			}
			set
			{
				if ((this._workpeakperiod != value))
				{
					this.OnworkpeakperiodChanging(value);
					this.SendPropertyChanging();
					this._workpeakperiod = value;
					this.SendPropertyChanged("workpeakperiod");
					this.OnworkpeakperiodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workdayquotafee", DbType="Float")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<float> workdayquotafee
		{
			get
			{
				return this._workdayquotafee;
			}
			set
			{
				if ((this._workdayquotafee != value))
				{
					this.OnworkdayquotafeeChanging(value);
					this.SendPropertyChanging();
					this._workdayquotafee = value;
					this.SendPropertyChanged("workdayquotafee");
					this.OnworkdayquotafeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workpeakfirstunit", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string workpeakfirstunit
		{
			get
			{
				return this._workpeakfirstunit;
			}
			set
			{
				if ((this._workpeakfirstunit != value))
				{
					this.OnworkpeakfirstunitChanging(value);
					this.SendPropertyChanging();
					this._workpeakfirstunit = value;
					this.SendPropertyChanged("workpeakfirstunit");
					this.OnworkpeakfirstunitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_worknonpeakfirstunit", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string worknonpeakfirstunit
		{
			get
			{
				return this._worknonpeakfirstunit;
			}
			set
			{
				if ((this._worknonpeakfirstunit != value))
				{
					this.OnworknonpeakfirstunitChanging(value);
					this.SendPropertyChanging();
					this._worknonpeakfirstunit = value;
					this.SendPropertyChanged("worknonpeakfirstunit");
					this.OnworknonpeakfirstunitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workpeakinunitfee", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public string workpeakinunitfee
		{
			get
			{
				return this._workpeakinunitfee;
			}
			set
			{
				if ((this._workpeakinunitfee != value))
				{
					this.OnworkpeakinunitfeeChanging(value);
					this.SendPropertyChanging();
					this._workpeakinunitfee = value;
					this.SendPropertyChanged("workpeakinunitfee");
					this.OnworkpeakinunitfeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workpeakoutunitfee", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string workpeakoutunitfee
		{
			get
			{
				return this._workpeakoutunitfee;
			}
			set
			{
				if ((this._workpeakoutunitfee != value))
				{
					this.OnworkpeakoutunitfeeChanging(value);
					this.SendPropertyChanging();
					this._workpeakoutunitfee = value;
					this.SendPropertyChanged("workpeakoutunitfee");
					this.OnworkpeakoutunitfeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_worknonpeakinunitfee", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string worknonpeakinunitfee
		{
			get
			{
				return this._worknonpeakinunitfee;
			}
			set
			{
				if ((this._worknonpeakinunitfee != value))
				{
					this.OnworknonpeakinunitfeeChanging(value);
					this.SendPropertyChanging();
					this._worknonpeakinunitfee = value;
					this.SendPropertyChanged("worknonpeakinunitfee");
					this.OnworknonpeakinunitfeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_worknonpeakoutunitfee", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public string worknonpeakoutunitfee
		{
			get
			{
				return this._worknonpeakoutunitfee;
			}
			set
			{
				if ((this._worknonpeakoutunitfee != value))
				{
					this.OnworknonpeakoutunitfeeChanging(value);
					this.SendPropertyChanging();
					this._worknonpeakoutunitfee = value;
					this.SendPropertyChanged("worknonpeakoutunitfee");
					this.OnworknonpeakoutunitfeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nonworkpeakperiod", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public string nonworkpeakperiod
		{
			get
			{
				return this._nonworkpeakperiod;
			}
			set
			{
				if ((this._nonworkpeakperiod != value))
				{
					this.OnnonworkpeakperiodChanging(value);
					this.SendPropertyChanging();
					this._nonworkpeakperiod = value;
					this.SendPropertyChanged("nonworkpeakperiod");
					this.OnnonworkpeakperiodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nonworkdayquotafee", DbType="Float")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public System.Nullable<float> nonworkdayquotafee
		{
			get
			{
				return this._nonworkdayquotafee;
			}
			set
			{
				if ((this._nonworkdayquotafee != value))
				{
					this.OnnonworkdayquotafeeChanging(value);
					this.SendPropertyChanging();
					this._nonworkdayquotafee = value;
					this.SendPropertyChanged("nonworkdayquotafee");
					this.OnnonworkdayquotafeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nonworkpeakfirstunit", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16)]
		public string nonworkpeakfirstunit
		{
			get
			{
				return this._nonworkpeakfirstunit;
			}
			set
			{
				if ((this._nonworkpeakfirstunit != value))
				{
					this.OnnonworkpeakfirstunitChanging(value);
					this.SendPropertyChanging();
					this._nonworkpeakfirstunit = value;
					this.SendPropertyChanged("nonworkpeakfirstunit");
					this.OnnonworkpeakfirstunitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nonworknonpeakfirstunit", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=17)]
		public string nonworknonpeakfirstunit
		{
			get
			{
				return this._nonworknonpeakfirstunit;
			}
			set
			{
				if ((this._nonworknonpeakfirstunit != value))
				{
					this.OnnonworknonpeakfirstunitChanging(value);
					this.SendPropertyChanging();
					this._nonworknonpeakfirstunit = value;
					this.SendPropertyChanged("nonworknonpeakfirstunit");
					this.OnnonworknonpeakfirstunitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nonworkpeakinunitfee", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=18)]
		public string nonworkpeakinunitfee
		{
			get
			{
				return this._nonworkpeakinunitfee;
			}
			set
			{
				if ((this._nonworkpeakinunitfee != value))
				{
					this.OnnonworkpeakinunitfeeChanging(value);
					this.SendPropertyChanging();
					this._nonworkpeakinunitfee = value;
					this.SendPropertyChanged("nonworkpeakinunitfee");
					this.OnnonworkpeakinunitfeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nonworkpeakoutunitfee", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=19)]
		public string nonworkpeakoutunitfee
		{
			get
			{
				return this._nonworkpeakoutunitfee;
			}
			set
			{
				if ((this._nonworkpeakoutunitfee != value))
				{
					this.OnnonworkpeakoutunitfeeChanging(value);
					this.SendPropertyChanging();
					this._nonworkpeakoutunitfee = value;
					this.SendPropertyChanged("nonworkpeakoutunitfee");
					this.OnnonworkpeakoutunitfeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nonworknonpeakinunitfee", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=20)]
		public string nonworknonpeakinunitfee
		{
			get
			{
				return this._nonworknonpeakinunitfee;
			}
			set
			{
				if ((this._nonworknonpeakinunitfee != value))
				{
					this.OnnonworknonpeakinunitfeeChanging(value);
					this.SendPropertyChanging();
					this._nonworknonpeakinunitfee = value;
					this.SendPropertyChanged("nonworknonpeakinunitfee");
					this.OnnonworknonpeakinunitfeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nonworknonpeakoutunitfee", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=21)]
		public string nonworknonpeakoutunitfee
		{
			get
			{
				return this._nonworknonpeakoutunitfee;
			}
			set
			{
				if ((this._nonworknonpeakoutunitfee != value))
				{
					this.OnnonworknonpeakoutunitfeeChanging(value);
					this.SendPropertyChanging();
					this._nonworknonpeakoutunitfee = value;
					this.SendPropertyChanged("nonworknonpeakoutunitfee");
					this.OnnonworknonpeakoutunitfeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fee", DbType="Float")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=22)]
		public System.Nullable<float> fee
		{
			get
			{
				return this._fee;
			}
			set
			{
				if ((this._fee != value))
				{
					this.OnfeeChanging(value);
					this.SendPropertyChanging();
					this._fee = value;
					this.SendPropertyChanged("fee");
					this.OnfeeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.workqueue")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CWorkQueueDto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _devicecode;
		
		private System.Nullable<int> _warehouse;
		
		private string _iccode;
		
		private System.Nullable<int> _swipecount;
		
		private string _waitsendtelegram;
		
		private System.Nullable<int> _priorityid;
		
		private System.Nullable<int> _tasktype;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndevicecodeChanging(System.Nullable<int> value);
    partial void OndevicecodeChanged();
    partial void OnwarehouseChanging(System.Nullable<int> value);
    partial void OnwarehouseChanged();
    partial void OniccodeChanging(string value);
    partial void OniccodeChanged();
    partial void OnswipecountChanging(System.Nullable<int> value);
    partial void OnswipecountChanged();
    partial void OnwaitsendtelegramChanging(string value);
    partial void OnwaitsendtelegramChanged();
    partial void OnpriorityidChanging(System.Nullable<int> value);
    partial void OnpriorityidChanged();
    partial void OntasktypeChanging(System.Nullable<int> value);
    partial void OntasktypeChanged();
    #endregion
		
		public CWorkQueueDto()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_devicecode", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<int> devicecode
		{
			get
			{
				return this._devicecode;
			}
			set
			{
				if ((this._devicecode != value))
				{
					this.OndevicecodeChanging(value);
					this.SendPropertyChanging();
					this._devicecode = value;
					this.SendPropertyChanged("devicecode");
					this.OndevicecodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_warehouse", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> warehouse
		{
			get
			{
				return this._warehouse;
			}
			set
			{
				if ((this._warehouse != value))
				{
					this.OnwarehouseChanging(value);
					this.SendPropertyChanging();
					this._warehouse = value;
					this.SendPropertyChanged("warehouse");
					this.OnwarehouseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iccode", DbType="VarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string iccode
		{
			get
			{
				return this._iccode;
			}
			set
			{
				if ((this._iccode != value))
				{
					this.OniccodeChanging(value);
					this.SendPropertyChanging();
					this._iccode = value;
					this.SendPropertyChanged("iccode");
					this.OniccodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swipecount", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<int> swipecount
		{
			get
			{
				return this._swipecount;
			}
			set
			{
				if ((this._swipecount != value))
				{
					this.OnswipecountChanging(value);
					this.SendPropertyChanging();
					this._swipecount = value;
					this.SendPropertyChanged("swipecount");
					this.OnswipecountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_waitsendtelegram", DbType="VarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string waitsendtelegram
		{
			get
			{
				return this._waitsendtelegram;
			}
			set
			{
				if ((this._waitsendtelegram != value))
				{
					this.OnwaitsendtelegramChanging(value);
					this.SendPropertyChanging();
					this._waitsendtelegram = value;
					this.SendPropertyChanged("waitsendtelegram");
					this.OnwaitsendtelegramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priorityid", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<int> priorityid
		{
			get
			{
				return this._priorityid;
			}
			set
			{
				if ((this._priorityid != value))
				{
					this.OnpriorityidChanging(value);
					this.SendPropertyChanging();
					this._priorityid = value;
					this.SendPropertyChanged("priorityid");
					this.OnpriorityidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasktype", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<int> tasktype
		{
			get
			{
				return this._tasktype;
			}
			set
			{
				if ((this._tasktype != value))
				{
					this.OntasktypeChanging(value);
					this.SendPropertyChanging();
					this._tasktype = value;
					this.SendPropertyChanged("tasktype");
					this.OntasktypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
}
#pragma warning restore 1591
