#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManagementLib
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_6096BJ")]
	public partial class CSQLRelateTableDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertCCarCustomerDto(CCarCustomerDto instance);
    partial void UpdateCCarCustomerDto(CCarCustomerDto instance);
    partial void DeleteCCarCustomerDto(CCarCustomerDto instance);
    partial void InsertCOperatorDto(COperatorDto instance);
    partial void UpdateCOperatorDto(COperatorDto instance);
    partial void DeleteCOperatorDto(COperatorDto instance);
    partial void InsertCDeviceStatusDto(CDeviceStatusDto instance);
    partial void UpdateCDeviceStatusDto(CDeviceStatusDto instance);
    partial void DeleteCDeviceStatusDto(CDeviceStatusDto instance);
    partial void InsertCICCardDto(CICCardDto instance);
    partial void UpdateCICCardDto(CICCardDto instance);
    partial void DeleteCICCardDto(CICCardDto instance);
    partial void InsertCCarLocationDto(CCarLocationDto instance);
    partial void UpdateCCarLocationDto(CCarLocationDto instance);
    partial void DeleteCCarLocationDto(CCarLocationDto instance);
    #endregion
		
		public CSQLRelateTableDataContext() : 
				base(global::DatabaseManagementLib.Properties.Settings.Default.db_6096BJConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CSQLRelateTableDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSQLRelateTableDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSQLRelateTableDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSQLRelateTableDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CCarCustomerDto> CCarCustomerDto
		{
			get
			{
				return this.GetTable<CCarCustomerDto>();
			}
		}
		
		public System.Data.Linq.Table<COperatorDto> COperatorDto
		{
			get
			{
				return this.GetTable<COperatorDto>();
			}
		}
		
		public System.Data.Linq.Table<CDeviceStatusDto> CDeviceStatusDto
		{
			get
			{
				return this.GetTable<CDeviceStatusDto>();
			}
		}
		
		public System.Data.Linq.Table<CICCardDto> CICCardDto
		{
			get
			{
				return this.GetTable<CICCardDto>();
			}
		}
		
		public System.Data.Linq.Table<CCarLocationDto> CCarLocationDto
		{
			get
			{
				return this.GetTable<CCarLocationDto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.carcustomer")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CCarCustomerDto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _userid;
		
		private string _username;
		
		private string _useraddr;
		
		private string _userphone;
		
		private string _usermobile;
		
		private string _carnumber;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnuseraddrChanging(string value);
    partial void OnuseraddrChanged();
    partial void OnuserphoneChanging(string value);
    partial void OnuserphoneChanged();
    partial void OnusermobileChanging(string value);
    partial void OnusermobileChanged();
    partial void OncarnumberChanging(string value);
    partial void OncarnumberChanged();
    #endregion
		
		public CCarCustomerDto()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_useraddr", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string useraddr
		{
			get
			{
				return this._useraddr;
			}
			set
			{
				if ((this._useraddr != value))
				{
					this.OnuseraddrChanging(value);
					this.SendPropertyChanging();
					this._useraddr = value;
					this.SendPropertyChanged("useraddr");
					this.OnuseraddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userphone", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string userphone
		{
			get
			{
				return this._userphone;
			}
			set
			{
				if ((this._userphone != value))
				{
					this.OnuserphoneChanging(value);
					this.SendPropertyChanging();
					this._userphone = value;
					this.SendPropertyChanged("userphone");
					this.OnuserphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usermobile", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string usermobile
		{
			get
			{
				return this._usermobile;
			}
			set
			{
				if ((this._usermobile != value))
				{
					this.OnusermobileChanging(value);
					this.SendPropertyChanging();
					this._usermobile = value;
					this.SendPropertyChanged("usermobile");
					this.OnusermobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carnumber", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string carnumber
		{
			get
			{
				return this._carnumber;
			}
			set
			{
				if ((this._carnumber != value))
				{
					this.OncarnumberChanging(value);
					this.SendPropertyChanging();
					this._carnumber = value;
					this.SendPropertyChanged("carnumber");
					this.OncarnumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.operator")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class COperatorDto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _optcode;
		
		private string _optname;
		
		private string _optpassword;
		
		private string _optphone;
		
		private string _optaddr;
		
		private System.Nullable<int> _opttype;
		
		private System.Nullable<int> _optpermission;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnoptcodeChanging(string value);
    partial void OnoptcodeChanged();
    partial void OnoptnameChanging(string value);
    partial void OnoptnameChanged();
    partial void OnoptpasswordChanging(string value);
    partial void OnoptpasswordChanged();
    partial void OnoptphoneChanging(string value);
    partial void OnoptphoneChanged();
    partial void OnoptaddrChanging(string value);
    partial void OnoptaddrChanged();
    partial void OnopttypeChanging(System.Nullable<int> value);
    partial void OnopttypeChanged();
    partial void OnoptpermissionChanging(System.Nullable<int> value);
    partial void OnoptpermissionChanged();
    #endregion
		
		public COperatorDto()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optcode", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string optcode
		{
			get
			{
				return this._optcode;
			}
			set
			{
				if ((this._optcode != value))
				{
					this.OnoptcodeChanging(value);
					this.SendPropertyChanging();
					this._optcode = value;
					this.SendPropertyChanged("optcode");
					this.OnoptcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optname", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string optname
		{
			get
			{
				return this._optname;
			}
			set
			{
				if ((this._optname != value))
				{
					this.OnoptnameChanging(value);
					this.SendPropertyChanging();
					this._optname = value;
					this.SendPropertyChanged("optname");
					this.OnoptnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optpassword", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string optpassword
		{
			get
			{
				return this._optpassword;
			}
			set
			{
				if ((this._optpassword != value))
				{
					this.OnoptpasswordChanging(value);
					this.SendPropertyChanging();
					this._optpassword = value;
					this.SendPropertyChanged("optpassword");
					this.OnoptpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optphone", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string optphone
		{
			get
			{
				return this._optphone;
			}
			set
			{
				if ((this._optphone != value))
				{
					this.OnoptphoneChanging(value);
					this.SendPropertyChanging();
					this._optphone = value;
					this.SendPropertyChanged("optphone");
					this.OnoptphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optaddr", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string optaddr
		{
			get
			{
				return this._optaddr;
			}
			set
			{
				if ((this._optaddr != value))
				{
					this.OnoptaddrChanging(value);
					this.SendPropertyChanging();
					this._optaddr = value;
					this.SendPropertyChanged("optaddr");
					this.OnoptaddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opttype", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<int> opttype
		{
			get
			{
				return this._opttype;
			}
			set
			{
				if ((this._opttype != value))
				{
					this.OnopttypeChanging(value);
					this.SendPropertyChanging();
					this._opttype = value;
					this.SendPropertyChanged("opttype");
					this.OnopttypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optpermission", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<int> optpermission
		{
			get
			{
				return this._optpermission;
			}
			set
			{
				if ((this._optpermission != value))
				{
					this.OnoptpermissionChanging(value);
					this.SendPropertyChanging();
					this._optpermission = value;
					this.SendPropertyChanged("optpermission");
					this.OnoptpermissionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.devicestatus")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CDeviceStatusDto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _warehouse;
		
		private int _devicecode;
		
		private System.Nullable<int> _tasktype;
		
		private System.Nullable<int> _isable;
		
		private System.Nullable<int> _isavailable;
		
		private System.Nullable<int> _devicemode;
		
		private string _deviceaddr;
		
		private System.Nullable<int> _devicetype;
		
		private System.Nullable<int> _halltype;
		
		private System.Nullable<int> _region;
		
		private System.Nullable<int> _isgetoutcar;
		
		private string _iccode;
		
		private System.Nullable<int> _instep;
		
		private System.Nullable<int> _outstep;
		
		private System.Nullable<int> _runstep;
		
		private System.Nullable<int> _warehousechange;
		
		private System.Nullable<int> _devicelayer;
		
		private System.Nullable<int> _prevnode;
		
		private System.Nullable<int> _currentnode;
		
		private System.Nullable<int> _queueprevnode;
		
		private System.Nullable<int> _queuecurrentnode;
		
		private string _scrloc;
		
		private string _desccloc;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnwarehouseChanging(int value);
    partial void OnwarehouseChanged();
    partial void OndevicecodeChanging(int value);
    partial void OndevicecodeChanged();
    partial void OntasktypeChanging(System.Nullable<int> value);
    partial void OntasktypeChanged();
    partial void OnisableChanging(System.Nullable<int> value);
    partial void OnisableChanged();
    partial void OnisavailableChanging(System.Nullable<int> value);
    partial void OnisavailableChanged();
    partial void OndevicemodeChanging(System.Nullable<int> value);
    partial void OndevicemodeChanged();
    partial void OndeviceaddrChanging(string value);
    partial void OndeviceaddrChanged();
    partial void OndevicetypeChanging(System.Nullable<int> value);
    partial void OndevicetypeChanged();
    partial void OnhalltypeChanging(System.Nullable<int> value);
    partial void OnhalltypeChanged();
    partial void OnregionChanging(System.Nullable<int> value);
    partial void OnregionChanged();
    partial void OnisgetoutcarChanging(System.Nullable<int> value);
    partial void OnisgetoutcarChanged();
    partial void OniccodeChanging(string value);
    partial void OniccodeChanged();
    partial void OninstepChanging(System.Nullable<int> value);
    partial void OninstepChanged();
    partial void OnoutstepChanging(System.Nullable<int> value);
    partial void OnoutstepChanged();
    partial void OnrunstepChanging(System.Nullable<int> value);
    partial void OnrunstepChanged();
    partial void OnwarehousechangeChanging(System.Nullable<int> value);
    partial void OnwarehousechangeChanged();
    partial void OndevicelayerChanging(System.Nullable<int> value);
    partial void OndevicelayerChanged();
    partial void OnprevnodeChanging(System.Nullable<int> value);
    partial void OnprevnodeChanged();
    partial void OncurrentnodeChanging(System.Nullable<int> value);
    partial void OncurrentnodeChanged();
    partial void OnqueueprevnodeChanging(System.Nullable<int> value);
    partial void OnqueueprevnodeChanged();
    partial void OnqueuecurrentnodeChanging(System.Nullable<int> value);
    partial void OnqueuecurrentnodeChanged();
    partial void OnscrlocChanging(string value);
    partial void OnscrlocChanged();
    partial void OndescclocChanging(string value);
    partial void OndescclocChanged();
    #endregion
		
		public CDeviceStatusDto()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_warehouse", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public int warehouse
		{
			get
			{
				return this._warehouse;
			}
			set
			{
				if ((this._warehouse != value))
				{
					this.OnwarehouseChanging(value);
					this.SendPropertyChanging();
					this._warehouse = value;
					this.SendPropertyChanged("warehouse");
					this.OnwarehouseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_devicecode", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public int devicecode
		{
			get
			{
				return this._devicecode;
			}
			set
			{
				if ((this._devicecode != value))
				{
					this.OndevicecodeChanging(value);
					this.SendPropertyChanging();
					this._devicecode = value;
					this.SendPropertyChanged("devicecode");
					this.OndevicecodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasktype", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<int> tasktype
		{
			get
			{
				return this._tasktype;
			}
			set
			{
				if ((this._tasktype != value))
				{
					this.OntasktypeChanging(value);
					this.SendPropertyChanging();
					this._tasktype = value;
					this.SendPropertyChanged("tasktype");
					this.OntasktypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isable", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<int> isable
		{
			get
			{
				return this._isable;
			}
			set
			{
				if ((this._isable != value))
				{
					this.OnisableChanging(value);
					this.SendPropertyChanging();
					this._isable = value;
					this.SendPropertyChanged("isable");
					this.OnisableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isavailable", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<int> isavailable
		{
			get
			{
				return this._isavailable;
			}
			set
			{
				if ((this._isavailable != value))
				{
					this.OnisavailableChanging(value);
					this.SendPropertyChanging();
					this._isavailable = value;
					this.SendPropertyChanged("isavailable");
					this.OnisavailableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_devicemode", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<int> devicemode
		{
			get
			{
				return this._devicemode;
			}
			set
			{
				if ((this._devicemode != value))
				{
					this.OndevicemodeChanging(value);
					this.SendPropertyChanging();
					this._devicemode = value;
					this.SendPropertyChanged("devicemode");
					this.OndevicemodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deviceaddr", DbType="VarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string deviceaddr
		{
			get
			{
				return this._deviceaddr;
			}
			set
			{
				if ((this._deviceaddr != value))
				{
					this.OndeviceaddrChanging(value);
					this.SendPropertyChanging();
					this._deviceaddr = value;
					this.SendPropertyChanged("deviceaddr");
					this.OndeviceaddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_devicetype", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.Nullable<int> devicetype
		{
			get
			{
				return this._devicetype;
			}
			set
			{
				if ((this._devicetype != value))
				{
					this.OndevicetypeChanging(value);
					this.SendPropertyChanging();
					this._devicetype = value;
					this.SendPropertyChanged("devicetype");
					this.OndevicetypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_halltype", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<int> halltype
		{
			get
			{
				return this._halltype;
			}
			set
			{
				if ((this._halltype != value))
				{
					this.OnhalltypeChanging(value);
					this.SendPropertyChanging();
					this._halltype = value;
					this.SendPropertyChanged("halltype");
					this.OnhalltypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public System.Nullable<int> region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this.OnregionChanging(value);
					this.SendPropertyChanging();
					this._region = value;
					this.SendPropertyChanged("region");
					this.OnregionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isgetoutcar", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public System.Nullable<int> isgetoutcar
		{
			get
			{
				return this._isgetoutcar;
			}
			set
			{
				if ((this._isgetoutcar != value))
				{
					this.OnisgetoutcarChanging(value);
					this.SendPropertyChanging();
					this._isgetoutcar = value;
					this.SendPropertyChanged("isgetoutcar");
					this.OnisgetoutcarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iccode", DbType="VarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public string iccode
		{
			get
			{
				return this._iccode;
			}
			set
			{
				if ((this._iccode != value))
				{
					this.OniccodeChanging(value);
					this.SendPropertyChanging();
					this._iccode = value;
					this.SendPropertyChanged("iccode");
					this.OniccodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_instep", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public System.Nullable<int> instep
		{
			get
			{
				return this._instep;
			}
			set
			{
				if ((this._instep != value))
				{
					this.OninstepChanging(value);
					this.SendPropertyChanging();
					this._instep = value;
					this.SendPropertyChanged("instep");
					this.OninstepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outstep", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public System.Nullable<int> outstep
		{
			get
			{
				return this._outstep;
			}
			set
			{
				if ((this._outstep != value))
				{
					this.OnoutstepChanging(value);
					this.SendPropertyChanging();
					this._outstep = value;
					this.SendPropertyChanged("outstep");
					this.OnoutstepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_runstep", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16)]
		public System.Nullable<int> runstep
		{
			get
			{
				return this._runstep;
			}
			set
			{
				if ((this._runstep != value))
				{
					this.OnrunstepChanging(value);
					this.SendPropertyChanging();
					this._runstep = value;
					this.SendPropertyChanged("runstep");
					this.OnrunstepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_warehousechange", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=17)]
		public System.Nullable<int> warehousechange
		{
			get
			{
				return this._warehousechange;
			}
			set
			{
				if ((this._warehousechange != value))
				{
					this.OnwarehousechangeChanging(value);
					this.SendPropertyChanging();
					this._warehousechange = value;
					this.SendPropertyChanged("warehousechange");
					this.OnwarehousechangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_devicelayer", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=18)]
		public System.Nullable<int> devicelayer
		{
			get
			{
				return this._devicelayer;
			}
			set
			{
				if ((this._devicelayer != value))
				{
					this.OndevicelayerChanging(value);
					this.SendPropertyChanging();
					this._devicelayer = value;
					this.SendPropertyChanged("devicelayer");
					this.OndevicelayerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prevnode", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=19)]
		public System.Nullable<int> prevnode
		{
			get
			{
				return this._prevnode;
			}
			set
			{
				if ((this._prevnode != value))
				{
					this.OnprevnodeChanging(value);
					this.SendPropertyChanging();
					this._prevnode = value;
					this.SendPropertyChanged("prevnode");
					this.OnprevnodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currentnode", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=20)]
		public System.Nullable<int> currentnode
		{
			get
			{
				return this._currentnode;
			}
			set
			{
				if ((this._currentnode != value))
				{
					this.OncurrentnodeChanging(value);
					this.SendPropertyChanging();
					this._currentnode = value;
					this.SendPropertyChanged("currentnode");
					this.OncurrentnodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_queueprevnode", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=21)]
		public System.Nullable<int> queueprevnode
		{
			get
			{
				return this._queueprevnode;
			}
			set
			{
				if ((this._queueprevnode != value))
				{
					this.OnqueueprevnodeChanging(value);
					this.SendPropertyChanging();
					this._queueprevnode = value;
					this.SendPropertyChanged("queueprevnode");
					this.OnqueueprevnodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_queuecurrentnode", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=22)]
		public System.Nullable<int> queuecurrentnode
		{
			get
			{
				return this._queuecurrentnode;
			}
			set
			{
				if ((this._queuecurrentnode != value))
				{
					this.OnqueuecurrentnodeChanging(value);
					this.SendPropertyChanging();
					this._queuecurrentnode = value;
					this.SendPropertyChanged("queuecurrentnode");
					this.OnqueuecurrentnodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrloc", DbType="VarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=23)]
		public string scrloc
		{
			get
			{
				return this._scrloc;
			}
			set
			{
				if ((this._scrloc != value))
				{
					this.OnscrlocChanging(value);
					this.SendPropertyChanging();
					this._scrloc = value;
					this.SendPropertyChanged("scrloc");
					this.OnscrlocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desccloc", DbType="VarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=24)]
		public string desccloc
		{
			get
			{
				return this._desccloc;
			}
			set
			{
				if ((this._desccloc != value))
				{
					this.OndescclocChanging(value);
					this.SendPropertyChanging();
					this._desccloc = value;
					this.SendPropertyChanged("desccloc");
					this.OndescclocChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.iccard")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CICCardDto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _iccode;
		
		private string _oldiccode;
		
		private string _phycode;
		
		private int _ictype;
		
		private int _icstatus;
		
		private System.Nullable<System.DateTime> _icnewtime;
		
		private System.Nullable<System.DateTime> _iclosstime;
		
		private System.Nullable<System.DateTime> _iclogouttime;
		
		private System.Nullable<System.DateTime> _icstarttime;
		
		private System.Nullable<System.DateTime> _icdeadline;
		
		private string _carlocaddr;
		
		private System.Nullable<int> _warehouse;
		
		private System.Nullable<int> _userid;
		
		private System.Nullable<int> _tariffid;
		
		private System.Nullable<int> _priorityid;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OniccodeChanging(string value);
    partial void OniccodeChanged();
    partial void OnoldiccodeChanging(string value);
    partial void OnoldiccodeChanged();
    partial void OnphycodeChanging(string value);
    partial void OnphycodeChanged();
    partial void OnictypeChanging(int value);
    partial void OnictypeChanged();
    partial void OnicstatusChanging(int value);
    partial void OnicstatusChanged();
    partial void OnicnewtimeChanging(System.Nullable<System.DateTime> value);
    partial void OnicnewtimeChanged();
    partial void OniclosstimeChanging(System.Nullable<System.DateTime> value);
    partial void OniclosstimeChanged();
    partial void OniclogouttimeChanging(System.Nullable<System.DateTime> value);
    partial void OniclogouttimeChanged();
    partial void OnicstarttimeChanging(System.Nullable<System.DateTime> value);
    partial void OnicstarttimeChanged();
    partial void OnicdeadlineChanging(System.Nullable<System.DateTime> value);
    partial void OnicdeadlineChanged();
    partial void OncarlocaddrChanging(string value);
    partial void OncarlocaddrChanged();
    partial void OnwarehouseChanging(System.Nullable<int> value);
    partial void OnwarehouseChanged();
    partial void OnuseridChanging(System.Nullable<int> value);
    partial void OnuseridChanged();
    partial void OntariffidChanging(System.Nullable<int> value);
    partial void OntariffidChanged();
    partial void OnpriorityidChanging(System.Nullable<int> value);
    partial void OnpriorityidChanged();
    #endregion
		
		public CICCardDto()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iccode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string iccode
		{
			get
			{
				return this._iccode;
			}
			set
			{
				if ((this._iccode != value))
				{
					this.OniccodeChanging(value);
					this.SendPropertyChanging();
					this._iccode = value;
					this.SendPropertyChanged("iccode");
					this.OniccodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oldiccode", DbType="VarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string oldiccode
		{
			get
			{
				return this._oldiccode;
			}
			set
			{
				if ((this._oldiccode != value))
				{
					this.OnoldiccodeChanging(value);
					this.SendPropertyChanging();
					this._oldiccode = value;
					this.SendPropertyChanged("oldiccode");
					this.OnoldiccodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phycode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string phycode
		{
			get
			{
				return this._phycode;
			}
			set
			{
				if ((this._phycode != value))
				{
					this.OnphycodeChanging(value);
					this.SendPropertyChanging();
					this._phycode = value;
					this.SendPropertyChanged("phycode");
					this.OnphycodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ictype", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public int ictype
		{
			get
			{
				return this._ictype;
			}
			set
			{
				if ((this._ictype != value))
				{
					this.OnictypeChanging(value);
					this.SendPropertyChanging();
					this._ictype = value;
					this.SendPropertyChanged("ictype");
					this.OnictypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_icstatus", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public int icstatus
		{
			get
			{
				return this._icstatus;
			}
			set
			{
				if ((this._icstatus != value))
				{
					this.OnicstatusChanging(value);
					this.SendPropertyChanging();
					this._icstatus = value;
					this.SendPropertyChanged("icstatus");
					this.OnicstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_icnewtime", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<System.DateTime> icnewtime
		{
			get
			{
				return this._icnewtime;
			}
			set
			{
				if ((this._icnewtime != value))
				{
					this.OnicnewtimeChanging(value);
					this.SendPropertyChanging();
					this._icnewtime = value;
					this.SendPropertyChanged("icnewtime");
					this.OnicnewtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iclosstime", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<System.DateTime> iclosstime
		{
			get
			{
				return this._iclosstime;
			}
			set
			{
				if ((this._iclosstime != value))
				{
					this.OniclosstimeChanging(value);
					this.SendPropertyChanging();
					this._iclosstime = value;
					this.SendPropertyChanged("iclosstime");
					this.OniclosstimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iclogouttime", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.Nullable<System.DateTime> iclogouttime
		{
			get
			{
				return this._iclogouttime;
			}
			set
			{
				if ((this._iclogouttime != value))
				{
					this.OniclogouttimeChanging(value);
					this.SendPropertyChanging();
					this._iclogouttime = value;
					this.SendPropertyChanged("iclogouttime");
					this.OniclogouttimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_icstarttime", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<System.DateTime> icstarttime
		{
			get
			{
				return this._icstarttime;
			}
			set
			{
				if ((this._icstarttime != value))
				{
					this.OnicstarttimeChanging(value);
					this.SendPropertyChanging();
					this._icstarttime = value;
					this.SendPropertyChanged("icstarttime");
					this.OnicstarttimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_icdeadline", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public System.Nullable<System.DateTime> icdeadline
		{
			get
			{
				return this._icdeadline;
			}
			set
			{
				if ((this._icdeadline != value))
				{
					this.OnicdeadlineChanging(value);
					this.SendPropertyChanging();
					this._icdeadline = value;
					this.SendPropertyChanged("icdeadline");
					this.OnicdeadlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carlocaddr", DbType="VarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string carlocaddr
		{
			get
			{
				return this._carlocaddr;
			}
			set
			{
				if ((this._carlocaddr != value))
				{
					this.OncarlocaddrChanging(value);
					this.SendPropertyChanging();
					this._carlocaddr = value;
					this.SendPropertyChanged("carlocaddr");
					this.OncarlocaddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_warehouse", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public System.Nullable<int> warehouse
		{
			get
			{
				return this._warehouse;
			}
			set
			{
				if ((this._warehouse != value))
				{
					this.OnwarehouseChanging(value);
					this.SendPropertyChanging();
					this._warehouse = value;
					this.SendPropertyChanged("warehouse");
					this.OnwarehouseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public System.Nullable<int> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tariffid", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public System.Nullable<int> tariffid
		{
			get
			{
				return this._tariffid;
			}
			set
			{
				if ((this._tariffid != value))
				{
					this.OntariffidChanging(value);
					this.SendPropertyChanging();
					this._tariffid = value;
					this.SendPropertyChanged("tariffid");
					this.OntariffidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priorityid", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16)]
		public System.Nullable<int> priorityid
		{
			get
			{
				return this._priorityid;
			}
			set
			{
				if ((this._priorityid != value))
				{
					this.OnpriorityidChanging(value);
					this.SendPropertyChanging();
					this._priorityid = value;
					this.SendPropertyChanged("priorityid");
					this.OnpriorityidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.carlocation")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CCarLocationDto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _carlocaddr;
		
		private System.Nullable<int> _warehouse;
		
		private System.Nullable<int> _carlocside;
		
		private System.Nullable<int> _carloccolumn;
		
		private System.Nullable<int> _carloclayer;
		
		private System.Nullable<int> _carlocstatus;
		
		private System.Nullable<int> _carloctype;
		
		private string _carlocsize;
		
		private string _iccode;
		
		private System.Nullable<int> _carwheelbase;
		
		private string _carsize;
		
		private System.Nullable<int> _isbackup;
		
		private System.Nullable<System.DateTime> _carintime;
		
		private System.Nullable<int> _priorityid;
		
		private System.Nullable<int> _region;
		
		private string _carnumber;
		
		private string _carpicture;
		
		private System.Nullable<int> _direction;
		
		private System.Nullable<int> _overallLg;
		
		private System.Nullable<int> _overhang;
		
		private System.Nullable<int> _carweight;
		
		private System.Nullable<int> _offcenter;
		
		private System.Nullable<int> _rearwheeldis;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncarlocaddrChanging(string value);
    partial void OncarlocaddrChanged();
    partial void OnwarehouseChanging(System.Nullable<int> value);
    partial void OnwarehouseChanged();
    partial void OncarlocsideChanging(System.Nullable<int> value);
    partial void OncarlocsideChanged();
    partial void OncarloccolumnChanging(System.Nullable<int> value);
    partial void OncarloccolumnChanged();
    partial void OncarloclayerChanging(System.Nullable<int> value);
    partial void OncarloclayerChanged();
    partial void OncarlocstatusChanging(System.Nullable<int> value);
    partial void OncarlocstatusChanged();
    partial void OncarloctypeChanging(System.Nullable<int> value);
    partial void OncarloctypeChanged();
    partial void OncarlocsizeChanging(string value);
    partial void OncarlocsizeChanged();
    partial void OniccodeChanging(string value);
    partial void OniccodeChanged();
    partial void OncarwheelbaseChanging(System.Nullable<int> value);
    partial void OncarwheelbaseChanged();
    partial void OncarsizeChanging(string value);
    partial void OncarsizeChanged();
    partial void OnisbackupChanging(System.Nullable<int> value);
    partial void OnisbackupChanged();
    partial void OncarintimeChanging(System.Nullable<System.DateTime> value);
    partial void OncarintimeChanged();
    partial void OnpriorityidChanging(System.Nullable<int> value);
    partial void OnpriorityidChanged();
    partial void OnregionChanging(System.Nullable<int> value);
    partial void OnregionChanged();
    partial void OncarnumberChanging(string value);
    partial void OncarnumberChanged();
    partial void OncarpictureChanging(string value);
    partial void OncarpictureChanged();
    partial void OndirectionChanging(System.Nullable<int> value);
    partial void OndirectionChanged();
    partial void OnoverallLgChanging(System.Nullable<int> value);
    partial void OnoverallLgChanged();
    partial void OnoverhangChanging(System.Nullable<int> value);
    partial void OnoverhangChanged();
    partial void OncarweightChanging(System.Nullable<int> value);
    partial void OncarweightChanged();
    partial void OnoffcenterChanging(System.Nullable<int> value);
    partial void OnoffcenterChanged();
    partial void OnrearwheeldisChanging(System.Nullable<int> value);
    partial void OnrearwheeldisChanged();
    #endregion
		
		public CCarLocationDto()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carlocaddr", DbType="VarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string carlocaddr
		{
			get
			{
				return this._carlocaddr;
			}
			set
			{
				if ((this._carlocaddr != value))
				{
					this.OncarlocaddrChanging(value);
					this.SendPropertyChanging();
					this._carlocaddr = value;
					this.SendPropertyChanged("carlocaddr");
					this.OncarlocaddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_warehouse", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> warehouse
		{
			get
			{
				return this._warehouse;
			}
			set
			{
				if ((this._warehouse != value))
				{
					this.OnwarehouseChanging(value);
					this.SendPropertyChanging();
					this._warehouse = value;
					this.SendPropertyChanged("warehouse");
					this.OnwarehouseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carlocside", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<int> carlocside
		{
			get
			{
				return this._carlocside;
			}
			set
			{
				if ((this._carlocside != value))
				{
					this.OncarlocsideChanging(value);
					this.SendPropertyChanging();
					this._carlocside = value;
					this.SendPropertyChanged("carlocside");
					this.OncarlocsideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carloccolumn", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<int> carloccolumn
		{
			get
			{
				return this._carloccolumn;
			}
			set
			{
				if ((this._carloccolumn != value))
				{
					this.OncarloccolumnChanging(value);
					this.SendPropertyChanging();
					this._carloccolumn = value;
					this.SendPropertyChanged("carloccolumn");
					this.OncarloccolumnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carloclayer", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<int> carloclayer
		{
			get
			{
				return this._carloclayer;
			}
			set
			{
				if ((this._carloclayer != value))
				{
					this.OncarloclayerChanging(value);
					this.SendPropertyChanging();
					this._carloclayer = value;
					this.SendPropertyChanged("carloclayer");
					this.OncarloclayerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carlocstatus", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<int> carlocstatus
		{
			get
			{
				return this._carlocstatus;
			}
			set
			{
				if ((this._carlocstatus != value))
				{
					this.OncarlocstatusChanging(value);
					this.SendPropertyChanging();
					this._carlocstatus = value;
					this.SendPropertyChanged("carlocstatus");
					this.OncarlocstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carloctype", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<int> carloctype
		{
			get
			{
				return this._carloctype;
			}
			set
			{
				if ((this._carloctype != value))
				{
					this.OncarloctypeChanging(value);
					this.SendPropertyChanging();
					this._carloctype = value;
					this.SendPropertyChanged("carloctype");
					this.OncarloctypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carlocsize", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string carlocsize
		{
			get
			{
				return this._carlocsize;
			}
			set
			{
				if ((this._carlocsize != value))
				{
					this.OncarlocsizeChanging(value);
					this.SendPropertyChanging();
					this._carlocsize = value;
					this.SendPropertyChanged("carlocsize");
					this.OncarlocsizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iccode", DbType="VarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public string iccode
		{
			get
			{
				return this._iccode;
			}
			set
			{
				if ((this._iccode != value))
				{
					this.OniccodeChanging(value);
					this.SendPropertyChanging();
					this._iccode = value;
					this.SendPropertyChanged("iccode");
					this.OniccodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carwheelbase", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public System.Nullable<int> carwheelbase
		{
			get
			{
				return this._carwheelbase;
			}
			set
			{
				if ((this._carwheelbase != value))
				{
					this.OncarwheelbaseChanging(value);
					this.SendPropertyChanging();
					this._carwheelbase = value;
					this.SendPropertyChanged("carwheelbase");
					this.OncarwheelbaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carsize", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string carsize
		{
			get
			{
				return this._carsize;
			}
			set
			{
				if ((this._carsize != value))
				{
					this.OncarsizeChanging(value);
					this.SendPropertyChanging();
					this._carsize = value;
					this.SendPropertyChanged("carsize");
					this.OncarsizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isbackup", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public System.Nullable<int> isbackup
		{
			get
			{
				return this._isbackup;
			}
			set
			{
				if ((this._isbackup != value))
				{
					this.OnisbackupChanging(value);
					this.SendPropertyChanging();
					this._isbackup = value;
					this.SendPropertyChanged("isbackup");
					this.OnisbackupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carintime", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public System.Nullable<System.DateTime> carintime
		{
			get
			{
				return this._carintime;
			}
			set
			{
				if ((this._carintime != value))
				{
					this.OncarintimeChanging(value);
					this.SendPropertyChanging();
					this._carintime = value;
					this.SendPropertyChanged("carintime");
					this.OncarintimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priorityid", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public System.Nullable<int> priorityid
		{
			get
			{
				return this._priorityid;
			}
			set
			{
				if ((this._priorityid != value))
				{
					this.OnpriorityidChanging(value);
					this.SendPropertyChanging();
					this._priorityid = value;
					this.SendPropertyChanged("priorityid");
					this.OnpriorityidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16)]
		public System.Nullable<int> region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this.OnregionChanging(value);
					this.SendPropertyChanging();
					this._region = value;
					this.SendPropertyChanged("region");
					this.OnregionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carnumber", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=17)]
		public string carnumber
		{
			get
			{
				return this._carnumber;
			}
			set
			{
				if ((this._carnumber != value))
				{
					this.OncarnumberChanging(value);
					this.SendPropertyChanging();
					this._carnumber = value;
					this.SendPropertyChanged("carnumber");
					this.OncarnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carpicture", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=18)]
		public string carpicture
		{
			get
			{
				return this._carpicture;
			}
			set
			{
				if ((this._carpicture != value))
				{
					this.OncarpictureChanging(value);
					this.SendPropertyChanging();
					this._carpicture = value;
					this.SendPropertyChanged("carpicture");
					this.OncarpictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direction", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=19)]
		public System.Nullable<int> direction
		{
			get
			{
				return this._direction;
			}
			set
			{
				if ((this._direction != value))
				{
					this.OndirectionChanging(value);
					this.SendPropertyChanging();
					this._direction = value;
					this.SendPropertyChanged("direction");
					this.OndirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overallLg", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=20)]
		public System.Nullable<int> overallLg
		{
			get
			{
				return this._overallLg;
			}
			set
			{
				if ((this._overallLg != value))
				{
					this.OnoverallLgChanging(value);
					this.SendPropertyChanging();
					this._overallLg = value;
					this.SendPropertyChanged("overallLg");
					this.OnoverallLgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overhang", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=21)]
		public System.Nullable<int> overhang
		{
			get
			{
				return this._overhang;
			}
			set
			{
				if ((this._overhang != value))
				{
					this.OnoverhangChanging(value);
					this.SendPropertyChanging();
					this._overhang = value;
					this.SendPropertyChanged("overhang");
					this.OnoverhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carweight", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=22)]
		public System.Nullable<int> carweight
		{
			get
			{
				return this._carweight;
			}
			set
			{
				if ((this._carweight != value))
				{
					this.OncarweightChanging(value);
					this.SendPropertyChanging();
					this._carweight = value;
					this.SendPropertyChanged("carweight");
					this.OncarweightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_offcenter", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=23)]
		public System.Nullable<int> offcenter
		{
			get
			{
				return this._offcenter;
			}
			set
			{
				if ((this._offcenter != value))
				{
					this.OnoffcenterChanging(value);
					this.SendPropertyChanging();
					this._offcenter = value;
					this.SendPropertyChanged("offcenter");
					this.OnoffcenterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rearwheeldis", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=24)]
		public System.Nullable<int> rearwheeldis
		{
			get
			{
				return this._rearwheeldis;
			}
			set
			{
				if ((this._rearwheeldis != value))
				{
					this.OnrearwheeldisChanging(value);
					this.SendPropertyChanging();
					this._rearwheeldis = value;
					this.SendPropertyChanged("rearwheeldis");
					this.OnrearwheeldisChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
}
#pragma warning restore 1591
